name=MyMatrixTools
version=1.0.0
author=sricharan battu sricharanbattu@gmail.com
maintainer=sricharan battu sricharanbattu@gmail.com
sentence=A high-level 2D mapping library for the Uno R4 WiFi LED Matrix.
paragraph=This library simplifies LED control on the 12x8 matrix by allowing row/column addressing (0-11, 0-7) and individual pixel removal, moving away from complex bitmasking.
category=Display
url=https://github.com/sricharanbattu/MyMatrixTools
architectures=renesas_uno
includes=MyMatrixTools.h